### ISSUE TITLE
Move to the W3C org on GitHub

### ISSUE THREAD

**Issue by jgraham** [w3c/wptdashboard#100]
All the other wpt infrastructure is hosted on the W3C GitHub org rather than in vendor-specific repositories. I would much prefer if this dashboard could align with the other components here.

**Comment by jeffcarp** [comment]
1. How would that work with licensing? Would we need to change it to a W3C BSD license? Even if not, we might still need to jump over a (hopefully small) legal hurdle to move it out of the current org.
2. There's already a project for collecting test results in the w3c org: https://github.com/w3c/test-results. Would the two projects live alongside each other?

**Comment by gsnedders** [comment]
> How would that work with licensing? Would we need to change it to a W3C BSD license? Even if not, we might still need to jump over a (hopefully small) legal hurdle to move it out of the current org.

No.

> There's already a project for collecting test results in the w3c org: https://github.com/w3c/test-results. Would the two projects live alongside each other?

Yes.

**Comment by bobholt** [comment]
From a logistical standpoint, this will have to be done by someone empowered to transfer repos out of the GoogleChrome org. I don't know how widespread that permission is: @foolip?

**Comment by foolip** [comment]
It looks like I can initiate a transfer of the repo, but I'll have to check if there's any process on our side before doing it. Who on the W3C side would have to accept this transfer? @plehegar? Any concerns?

**Comment by plehegar** [comment]
No concern on our side I think. Mike or I can do it.

Philippe

On August 31, 2017 9:39:16 AM EDT, "Philip Jägenstedt" <notifications@github.com> wrote:
>It looks like I can initiate a transfer of the repo, but I'll have to
>check if there's any process on our side before doing it. Who on the
>W3C side would have to accept this transfer? @plehegar? Any concerns?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by foolip** [comment]
Is the repo name OK? Is there a naming convention for the other wpt repos?

**Comment by plehegar** [comment]
The name is ok. We'd been using the prefix wpt for most of those. 

Philippe

On August 31, 2017 10:21:16 AM EDT, "Philip Jägenstedt" <notifications@github.com> wrote:
>Is the repo name OK? Is there a naming convention for the other wpt
>repos?

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by foolip** [comment]
OK, I have the necessary approvals. I tried doing it myself, but it fails because I can't create new repos in the w3c org. @sideshowbarker, I've made you an admin of this repo, can you transfer it for us?

**Comment by foolip** [comment]
It's fine if the "web platform test dashboard" admin team isn't preserved.

**Comment by sideshowbarker** [comment]
OK, moved

> It's fine if the "web platform test dashboard" admin team isn't preserved.

Github anyway wouldn’t show me the members of that team (because I guess it’s not public), so I couldn’t preserve it anyway. But all y’all have admin perms now, so if there’s anybody else you want to give write access or admin access to, you can use https://github.com/w3c/wptdashboard/settings/collaboration to do that.

**Comment by foolip** [comment]
Thanks Mike, and thanks James for filing!
