### ISSUE TITLE
Chrome: Many css/css-position-3 tests failing on wpt.fyi, but pass in Chrome's own test infra

### ISSUE THREAD

**Issue by stephenmcgruer** [w3c/wptdashboard#113]
http://wpt.fyi/css/css-position-3 - as of 2017/09/11, it looks like 30 of the css-position-3 tests fail on wpt.fyi, but if you look at Chrome's own TestExpectations file[1], we only blacklist 5 tests as failing. This means that the other 25 do run in Chrome's LayoutTest infrastructure, and pass on every commit.

1: https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/TestExpectations?l=121

**Comment by stephenmcgruer** [comment]
This is likely caused by https://github.com/w3c/web-platform-tests/issues/6986 - the tests that are passing are not reftests.

**Comment by gsnedders** [comment]
Also see #97. Should probably just repurpose that issue?
