### ISSUE TITLE
Sauce builds are stuck

### ISSUE THREAD

**Issue by jeffcarp** [w3c/wptdashboard#115]
The last build for Edge was Sept 6; Safari Sept 7. Something might have gone wrong in `instance-2`.

**Comment by bobholt** [comment]
I went to check the log. It's 2.5GB. I'm trying to download it now to see what's wrong and then I'll empty it.

**Comment by jeffcarp** [comment]
I logged into the instance and saw a lot of `wptrunner` and `gsutil` processes laying around but nothing being written to the logfile. I restarted the VM and truncated the logfile (sorry, I intended to preserve the last 50K lines but I messed up). A fresh invocation of Edge+Sauce seems to run fine (for the first few minutes). We'll see if that helps in ~3 hours when the crontab kicks off the run.

**Comment by jeffcarp** [comment]
That seems to have fixed things! (for now 👻)
