### ISSUE TITLE
To run tests you need both py2 and py3

### ISSUE THREAD

**Issue by AutomatedTester** [w3c/wptdashboard#120]
TO run the wpt tests, which only work on py2, the script that runs them is written for py3. This creates an interesting dynamic to make it work.

We need to pick one or other

**Comment by jgraham** [comment]
Updating wpt/wptrunner to use Python 3 is likely a lot of work. I can see the rationale for picking Python 3 for new projects, but I don't know if it's worthwhile in this case.
