### ISSUE TITLE
Consider calling tests just "Test" instead of "Subtest"

### ISSUE THREAD

**Issue by foolip** [w3c/wptdashboard#130]
In http://wpt.fyi/speech-api/historical.html the first column says "Subtest". In testharness.js the terminology is that each of these is a test. The whole file is just a file, a way of grouping tests. This is the terminology that @jgraham uses and that I try to emulate :)

**Comment by lukebjerring** [comment]
This issue was moved to web-platform-tests/wpt.fyi#29
