### ISSUE TITLE
Show which revision everything related to wpt-dashboard is running 

### ISSUE THREAD

**Issue by AutomatedTester** [w3c/wptdashboard#144]
I have fixed how firefox is running to fix issue #90 but still seeing the results.

Currently there is no way to see when everything was updated and what revision it is on. It would be good to know that so that if issues arent fixed we can try figure it out

**Comment by jeffcarp** [comment]
Do you mean the revision of wptdashboard?

**Comment by jugglinmike** [comment]
See also https://github.com/w3c/wptdashboard/issues/352

**Comment by lukebjerring** [comment]
This issue was moved to web-platform-tests/wpt.fyi#25
