### ISSUE TITLE
Results not shown for files with certain extensions.

### ISSUE THREAD

**Issue by gsnedders** [w3c/wptdashboard#147]
See e.g. http://wpt.fyi/css/CSS2/abspos/abspos-containing-block-initial-001.xht

This page is totally blank. There's no results, and no link to the test on w3c-test.org. If you go up to the containing directory, you'll find results for this test.

**Comment by jeffcarp** [comment]
Looks like this is true for any `*.xht` test. It's probably a bug in our test filename heuristics.

**Comment by gsnedders** [comment]
And `*.xhtml`. Why do we have test filename heuristics at all, aren't we just using the manifest data?

**Comment by jgraham** [comment]
Also for the `.py` tests for webdriver.
