### ISSUE TITLE
Date of run should be based on commit history (date for same commit can differ)

### ISSUE THREAD

**Issue by foolip** [w3c/wptdashboard#154]
wpt.fyi looks like this today:
<img width="528" alt="screen shot 2017-10-14 at 11 32 21 am" src="https://user-images.githubusercontent.com/498917/31574607-777b29da-b0d3-11e7-80b3-cda80300e973.png">

Three of the runs are for 770bad1295, but the dates are Oct 13 and Oct 14. This is probably because the Edge run took longer.

Even if runs are eventually much faster, we should *not* show different dates if they just happen to cross the date line.

**Comment by lukebjerring** [comment]
https://github.com/w3c/wptdashboard/pull/254 adds the ability to explicitly set the 'created_at' field in the JSON body when the query parameter ?retroactive=true is present (which is used in the script for copying prod runs to a local instance).

**Comment by lukebjerring** [comment]
@foolip 'we should show different dates' - is that supposed to be 'should not'? Otherwise isn't that already WAI?

**Comment by foolip** [comment]
Oops, missed an important word there, edited.

**Comment by foolip** [comment]
I noticed this problem again today:
<img width="528" alt="screen shot 2018-01-22 at 7 00 45 pm" src="https://user-images.githubusercontent.com/498917/35219796-957c97e4-ffa6-11e7-9e82-4d208872aff4.png">

Commit dates in UTC were:
53c5bf648c: 2018-01-03 09:18:44
03d67ae5d9: 2018-01-16 00:01:56
e856c3db7b: 2018-01-18 00:14:35
a9ed3553eb: 2018-01-18 22:55:13

Chrome in particular is very behind.

**Comment by foolip** [comment]
Updated the title again to clarify that I don't necessarily think we should just use the committer date, since that might not be monotonically increasing. It would be an improvement over using the wall clock time though, as it very rarely is anything other than the real update time.

**Comment by rwaldron** [comment]
@mdittmer 

> To clarify, is this a UI concern? 

Partly. It appears that what the displayed date represents is unclear: I believe @foolip assumed that it was the commit time (I used to think that was the case as well). 

> IMHO, the underlying data should store both the commit time and the date-of-run time. 

Agreed, but it presently does not (also... adding that now would also require backfilling all of the existing entities.)

**Comment by boazsender** [comment]
+1 for number 3 to close this issue

I then suggest opening a new issue to implement number 4 in the future as a new feature.

**Comment by rwaldron** [comment]
> I then suggest opening a new issue to implement number 4 in the future as a new feature.

👍 

File the following issues: 

1. Update shared model to include `commit_date`
2. Update GCP entity
3. Backfill commit dates

**Comment by lukebjerring** [comment]
IMHO, I don't think we should duplicate the field from Git into the WPTD datastore  (TestRun metadata). If the commit-date of the repo is needed in the UI, it's available via GitHub's API,
e.g. https://api.github.com/repos/w3c/wptdashboard/commits/cf5844f22e

Note that for late (manual) runs, date_created field can be retroactive when posting results, https://github.com/w3c/wptdashboard/blob/master/webapp/api_handlers.go#L181-L184

Are the runs happening sequentially? Is there actually sometimes a whole day between different browsers starting?

**Comment by mariestaver** [comment]
Created #402 for item 4 above -- I believe in combination with @rwaldron 's commit (which addresses item 3), this takes care what we want to do to about this issue.  Thanks everyone!  Closing this issue.
