### ISSUE TITLE
Move Chrome to running in Docker on Jenkins

### ISSUE THREAD

**Issue by jeffcarp** [w3c/wptdashboard#205]
Chrome is now the last platform we run in a VM. The easiest path forward would be to bake a Chrome image into the Docker container and test against that. We could also investigate adding `--install-browser` support (#141) for Chrome, which is how we manage Firefox binaries now.

**Comment by jugglinmike** [comment]
I'm closing this issue because we no longer use the Jenkins project for test results collection
