### ISSUE TITLE
Chrome and Firefox runs are often incomplete

### ISSUE THREAD

**Issue by jeffcarp** [w3c/wptdashboard#210]
For the last 2-3 FF runs on Jenkins, it has only run 25-50% of the tests. I've reverted these runs so they don't show up on wpt.fyi.

Example run:
- https://ci.wpt.fyi/job/firefox-nightly/5/

**Comment by jeffcarp** [comment]
Happened again today :imp: 

- https://wpt.fyi/?sha=8e93ce8cd0
- https://ci.wpt.fyi/job/firefox-nightly/10/

The test files that do end up being run have been inconsistent (e.g. it's not just skipping X tests)

**Comment by jgraham** [comment]
Nothing is jumping out at me from the logs.

**Comment by jeffcarp** [comment]
@jgraham do you think this could be related to https://github.com/w3c/web-platform-tests/pull/5774? The landed patch in that PR is different from the patch we were applying before (which just caught and ignored the exception).

**Comment by jgraham** [comment]
It could be. In theory that only happens if the browser fails to start in the time limit, and we need to retry. Catching the exception ought not to work, so if there's a bug here I need to look more closely.

**Comment by mariestaver** [comment]
Closing this issue:  Firefox is working now, and the Chrome run problem is (now) known and being addressed in issue #401
