### ISSUE TITLE
Jenkins test in Travis CI broken by WPT treatment of /etc/hosts

### ISSUE THREAD

**Issue by mdittmer** [w3c/wptdashboard#230]
Example of error:
https://travis-ci.org/w3c/wptdashboard/builds/300329719#L2916

This appears to be the same as the issue described here:
https://blog.jonathanargentiero.com/docker-sed-cannot-rename-etcsedl8ysxl-device-or-resource-busy/

**Comment by Hexcles** [comment]
Perhaps use the `--add-host` argument of `docker run` instead. https://docs.docker.com/engine/reference/run/#managing-etchosts

**Comment by jugglinmike** [comment]
I'm closing this issue because we no longer use the Jenkins project for test results collection
