### ISSUE TITLE
Previous runs view not working

### ISSUE THREAD

**Issue by RByers** [w3c/wptdashboard#232]
When I click on [recent runs](https://wpt.fyi/test-runs) and select [a commit](https://wpt.fyi/?sha=04892735ed), I don't see anything.  Console says:
```
/api/run?browser=safari&sha=04892735ed Failed to load resource: the server responded with a status of 404 ()
wpt-results.html:259 Uncaught (in promise) SyntaxError: Unexpected token p in JSON at position 4
/api/run?browser=edge&sha=04892735ed Failed to load resource: the server responded with a status of 404 ()
```

I'm not sure if this ever worked, but I didn't find an existing bug.  /cc @mattl @jeffcarp @lukebjerring

**Comment by lukebjerring** [comment]
Known and fixed by https://github.com/w3c/wptdashboard/pull/226
