### ISSUE TITLE
Most chrome and firefox results currently missing

### ISSUE THREAD

**Issue by RByers** [w3c/wptdashboard#233]
Currently I see no results for Chrome or Firefox anywhere, eg. one sub-page
![screenshot 2017-11-11 at 11 21 23 am](https://user-images.githubusercontent.com/1280419/32691245-69b9ec40-c6b9-11e7-9116-748c49ae069d.png)

Individual tests say "no results found".  Obviously this makes the dashboard pretty useless and so is urgent.

@mattl @jeffcarp @foolip @lukebjerring

**Comment by RByers** [comment]
Was hoping to use previous runs to work around this, but that's broken too - #232

**Comment by lukebjerring** [comment]
At a guess, the run must have only been partial (why is not something I'd
speculate at). The frontend is just pulling the results - you can use
https://wpt.fyi/json?platform=chrome to see it redirects to
https://storage.googleapis.com/wptd/04892735ed/chrome-63.0-linux-summary.json.gz

**Comment by foolip** [comment]
Since https://github.com/w3c/wptdashboard/issues/235 is assigned to @lukebjerring and lacking a suspicion that this has anything to do with Luke's changes, assigning to @mattl for initial debugging.

**Comment by mattl** [comment]
I'm looking at this. I would appreciate being able to revert things in GitHub and have access to the settings tab.

**Comment by rwaldron** [comment]
The last complete run for Chrome was 6ed1ba18d0:  https://storage.googleapis.com/wptd/6ed1ba18d0/chrome-63.0-linux-summary.json.gz

**Comment by mattl** [comment]
I got permissions from @jgraham

**Comment by rwaldron** [comment]
While the bigger picture issue is addressed (guarding against incomplete test run data becoming the "latest"), I recommend manually setting the "latest"  to 6ed1ba18d0.

**Comment by mattl** [comment]
Okay, things are looking much better. 

![wpt fyi_](https://user-images.githubusercontent.com/33296/32753236-160abeca-c89a-11e7-961c-78fb4917ccc8.png)

This will likely break again soon. Right now I had to revert what we're showing to Nov 4th for Chrome and a similar date for Firefox (thanks @jeffcarp). I have assigned myself https://github.com/w3c/wptdashboard/issues/234 and will be prioritizing my work around that.

Right now, this process is a little tricky to figure out a good run:

* Look at https://wpt.fyi/test-runs for a SHA.
* Go to https://storage.googleapis.com/wptd/$SHA/$BROWSWER-summary.json.gz
* Wait for the JSON to load
* In browser, search for ": [
* See how many results are in the file for that search (should be approx. 23,000)
* Repeat until a good file is found
* Once found, open up [Cloud Console](https://console.cloud.google.com/datastore/entities/query?project=wptdashboard&ns=&kind=TestRun&sortDir=DESCENDING&sortCol=CreatedAt) and rename all runs after the desired SHA to have a name like incomplete-chrome or incomplete-firefox.

This is the messy but workable solution right now. 

First thing I'm going to do is make a little tool that makes finding a good recent SHA easy, and then use that to guide my work on #234

**Comment by mattl** [comment]
@jeffcarp pointed me to @lukebjerring's https://github.com/w3c/wptdashboard/blob/master/util/diff_runs.py which will help too. Thanks Luke!

**Comment by mattl** [comment]
Incomplete run again last night for Chrome and Firefox. @jeffcarp -- I can see most browsers are running from Jenkins now. What is the situation with Chrome?

**Comment by mattl** [comment]
(I changed the relevant entries in Cloud Console so we have a good looking, but outdated dashboard again)

**Comment by lukebjerring** [comment]
This appears to be the same issue as https://github.com/w3c/wptdashboard/issues/210

**Comment by lukebjerring** [comment]
Note that the recent deployment included behaviour for https://github.com/w3c/wptdashboard/issues/138 (show a complete run), which may make your workaround more, or less, difficult to employ.

**Comment by mattl** [comment]
Right, now seeing results from September 24th!

**Comment by lukebjerring** [comment]
Let's revert https://github.com/w3c/wptdashboard/pull/199 then, seems like it's buggy.

**Comment by foolip** [comment]
#199 was reverted in https://github.com/w3c/wptdashboard/pull/240, so once deployed this issue should be closed?

**Comment by lukebjerring** [comment]
Deployed. We can continue general solving of the underlying problem in https://github.com/w3c/wptdashboard/issues/210

**Comment by mattl** [comment]
@lukebjerring Can you explain to me here or IRC how this deploy is performed? I'd like to be able to do this myself and currently have no way to do that.
