### ISSUE TITLE
Test result pages break after working the first time

### ISSUE THREAD

**Issue by mdittmer** [w3c/wptdashboard#235]
Example:

I followed links to get to https://wpt.fyi/2dcontext/fill-and-stroke-styles/2d.fillStyle.parse.css-color-4-hsl-2.html

I saw the results the first time I loaded the page. When I refresh the page I see no results.

@lukebjerring could this be related to the new endpoints you've been integrating?

**Comment by foolip** [comment]
I saw this too when loading https://wpt.fyi/subresource-integrity/subresource-integrity.sub.html and then reloading.

Assigning to @mattl to investigate what's going on.

**Comment by foolip** [comment]
Actually, in a 1:1 with @mdittmer right now and he thinks it's likely that this is related to @lukebjerring's changes, so assigning to Luke first.

**Comment by lukebjerring** [comment]
Caused by the intermediate TestRun JSON fetch not being triggered when loading an individual result directly.

**Comment by lukebjerring** [comment]
Fixed via https://github.com/w3c/wptdashboard/pull/237

**Comment by foolip** [comment]
Confirmed to be working! @lukebjerring, I guess this means that we're now auto-deploying changes? (I expected it to not work until @jeffcarp got to work.)

**Comment by lukebjerring** [comment]
We're working on documenting and sharing the deployment process, as don't
want to overload @jeffcarp (nor bottleneck).

I did this deployment in particular.
