### ISSUE TITLE
Wrong results shown after navigation (refreshing the page gives the right result)

### ISSUE THREAD

**Issue by Hexcles** [w3c/wptdashboard#258]
Reproduction steps:

1. Open any test result (e.g. https://wpt.fyi/WebCryptoAPI/idlharness.https.html)
2. Click on the path nav bar to navigate to another test file (e.g. clicking on `WebCryptoAPI`, and then selecting `idlharness.html`, which should take you to https://wpt.fyi/WebCryptoAPI/idlharness.html)
3. Results shown on the page are results from the previous test file (`idlharness.https.html`).
4. Refreshing the page gives the right result for the current file (`idlharness.html`).

I've tried the steps above in incognito mode with cache disabled, too. The bug can still be observed.

**Comment by lukebjerring** [comment]
Broken by https://github.com/w3c/wptdashboard/pull/237 which re-jigged the way the test-file was refreshed.
