### ISSUE TITLE
Automatically publish Jenkins running container

### ISSUE THREAD

**Issue by jeffcarp** [w3c/wptdashboard#289]
cc @mattl 

The container that lives at [gcr.io/wptdashboard/wptd-testrun-jenkins](gcr.io/wptdashboard/wptd-testrun-jenkins) should be automatically rebuilt and updated every time a commit lands on master. This is the URL the Jenkins bots pull their image from, so automatically updating it will help us catch problems much quicker and avoid having production fall out of sync with master.

There are two ways we can do this:
- Add GCP credentials to our Travis run, have Travis push a new image after it builds the master branch
- Use GCP [Container Builder](https://cloud.google.com/container-builder/docs/)

**Comment by jugglinmike** [comment]
We no longer use the Jenkins project for test results collection
