### ISSUE TITLE
Announce commit or commits to test for internal and external runs

### ISSUE THREAD

**Issue by foolip** [w3c/wptdashboard#292]
Background:
* The original [Design Doc: WPT Dashboard](https://docs.google.com/document/d/1eGsFVBaeg8q1LYowDj62EA-yXJgGuKX9A5FIkmejMxA/edit?usp=sharing) had "one build per platform every morning that runs all WPT tests against one WPT revision" and then, as a simplification, "Instead of bots pulling the WPT revision to test against, they just test against the first WPT revision that day".
* https://github.com/w3c/wptdashboard/issues/40 is about that simplification although the original central "pick a revision" part no longer exists.
* [Consistent results for all browsers are updated every 24 hours](https://docs.google.com/document/d/1GZquS8Jra47E5hIMH2ObOb_7oQFgk8f9MptUAjF0LFI/edit#heading=h.qxotds9ar227) will require results from the same commit. "Picking a WPT commit" is part of the description, although it's not strictly required to achieve the objective.
* https://github.com/w3c/wptdashboard/issues/164 is about testing much more frequently than once a day.
* https://github.com/w3c/wptdashboard/issues/290 is about supporting external runs.

Those are the "use cases" to solve. Proposed solution and title of this issue:

Have an endpoint like https://wpt.fyi/api/shas that returns at the very least *a* commit to test, but more usefully a set of commits which is either pre-prioritized or has enough information that consumers could decide which to prioritize running first.

The minimum useful behavior for runners would be to prioritize finishing a well-defined "today's sha".

**Comment by foolip** [comment]
@mattl, would you consider this resolve by https://sha.wpt.fyi/? I think a bit more would be required to support external runs, but it's fine to keep that to https://github.com/w3c/wptdashboard/issues/290.

**Comment by jugglinmike** [comment]
As of gh-522, we collect results on a regular schedule (once every 6 hours for Chrome and Firefox, once every 2 days for Edge and Safari). We identify the latest commit to WPT at this moment, and all subsequent testing operations reference that commit via its git SHA sum.
