### ISSUE TITLE
Data for a run of commit dd44fd07c5 exists, but the commit does not

### ISSUE THREAD

**Issue by foolip** [w3c/wptdashboard#293]
`gsutil ls gs://wptd/dd44fd07c5/` shows some results, but dd44fd07c5 is not a commit in web-platform-tests.

This could be because web-platform-tests history has been rewritten, but could also be an actual bug. @jeffcarp, is there any way to investigate this?

**Comment by foolip** [comment]
The other 148 directories in gs://wptd/ do correspond to existing commits.

**Comment by jgraham** [comment]
If the history has been rewritten I'm not aware of it. You didn't do a run on a branch for some reason did you?

**Comment by foolip** [comment]
Could be from a test run of some sorts, I don't know, hoping that @jeffcarp has clues. It's probably harmless and the directory can be removed.

**Comment by lukebjerring** [comment]
That will be a local test run.
FYI:

    Creation time:          Mon, 24 Jul 2017 18:46:28 GMT

**Comment by foolip** [comment]
I don't know if anything will be made simpler if all runs correspond to commits, but if there's no value in keeping this around, maybe delete it just to not confuse me next time? @jeffcarp, how to remove it?

**Comment by rwaldron** [comment]
>  but if there's no value in keeping this around, maybe delete it just to not confuse me next time?

I've marked this directory to be deleted.

**Comment by foolip** [comment]
Thanks! Does that mean it's gone from GCS as well, or what does "marking" mean?
