### ISSUE TITLE
Latest Chrome run is mostly empty

### ISSUE THREAD

**Issue by gsnedders** [w3c/wptdashboard#312]
https://wpt.fyi/?sha=dd01f9ab60

**Comment by mdittmer** [comment]
https://wpt.fyi/test-runs suggests the latest Chrome run is
https://wpt.fyi/?sha=6ed1ba18d0

On Thu, Nov 30, 2017 at 10:01 AM, Geoffrey Sneddon <notifications@github.com

**Comment by gsnedders** [comment]
@mdittmer well, it was definitely there earlier! I presume someone nuked it.
