### ISSUE TITLE
All file-level Chrome and Firefox results are "(results not found)"

### ISSUE THREAD

**Issue by foolip** [w3c/wptdashboard#344]
Compare:
https://wpt.fyi/html/dom
https://wpt.fyi/html/dom/historical.html

In the higher-level view, it's clear that the tests have run. But they cannot be seen. This appears to be the case everywhere right now, greatly reducing the usefulness of wpt.fyi.

**Comment by foolip** [comment]
I'm labeling this as urgent, and I do think it currently trumps https://github.com/w3c/wptdashboard/issues/273. (Having more fresh results doesn't help if they cannot be used.)

Hopefully this is a simple bug.

**Comment by lukebjerring** [comment]
Issue was that the ResultsURL field's URLs had a trailing `?` - I suspect they were entered manually.

**Comment by mattl** [comment]
Apologies, I was adding ? to the end as I was having issues in December with partial runs on the same SHA being cached.

**Comment by foolip** [comment]
Yay, it works, thanks @lukebjerring!
