### ISSUE TITLE
Edge running an old checkout of tests?

### ISSUE THREAD

**Issue by mikewest** [w3c/wptdashboard#354]
Edge's latest run is from the 13th, but it looks like it's using a WPT checkout from mid-December: https://wpt.fyi/cookies/secure?sha=13eaad17a4. Ideally, it would be using tip-of-tree.

**Comment by mattl** [comment]
I'll get this fixed.

**Comment by mattl** [comment]
This is now running against HEAD, I'll close this once we have a successful run.

**Comment by mattl** [comment]
Success on an up to date checkout.
