### ISSUE TITLE
wpt.fyi/* routes are future hostile

### ISSUE THREAD

**Issue by rwaldron** [w3c/wptdashboard#374]
If https://github.com/w3c/web-platform-tests were to ever grow a new top level directory for some hypothetical spec named "api", "interop", "results", or "test-run", then routing in webapp/main.go becomes ambiguous.

**Comment by boazsender** [comment]
+1, test results routes should be name spaced.

For the `/interop/` example in #372, it's worth mentioning that the [compat spec](https://compat.spec.whatwg.org) could have just as easily been called "interop". We have tests for that spec, and the `/compat` route is in the global name space (see https://wpt.fyi/compat).

**Comment by rwaldron** [comment]
Honestly, the only truly safe solution is the one that breaks all the existing inbound links, ie. wpt.fyi/test/path.html => wpt.fyi/some-safe-path/test/path.html, but that might be the price to pay for rushing this out.

**Comment by lukebjerring** [comment]
We can redirect the current wildcard matches to /some-safe-path/, mitigating breakages to current links to clashes only.

**Comment by rwaldron** [comment]
@lukebjerring yep, that's what was I thinking (and what brought me back here just now to follow up on). I don't want to rush into this yet.

**Comment by lukebjerring** [comment]
This issue is related to the Q1 OKR of switching the default view to the interop view:
https://docs.google.com/document/d/1ojlLDiRruI4e95Z7JQ10JQPRMiQHd_40rBkYCL6IJqw/edit#heading=h.v93ez0y7fvmy

**Comment by lukebjerring** [comment]
This issue was moved to web-platform-tests/wpt.fyi#13
