### ISSUE TITLE
populate_dev_data.go not functioning correctly

### ISSUE THREAD

**Issue by lukebjerring** [w3c/wptdashboard#378]

**Comment by lukebjerring** [comment]
Note that https://github.com/w3c/wptdashboard/pull/380 is a browser-based method for acquiring application credentials.

**Comment by lukebjerring** [comment]
@rwaldron - Looks like this auto-closed via the "Fixes #378" comment in #381. Can you confirm that you're now able to run the script locally (including the instructions being reasonable)?

**Comment by rwaldron** [comment]
Sorry I missed this—yes, this is functioning correctly now.
