### ISSUE TITLE
Look into using Travis to deploy master on green

### ISSUE THREAD

**Issue by jeffcarp** [w3c/wptdashboard#39]
Would be nice for a couple reasons:

1. Contributors who land their approved PRs wouldn't need to reach out separately for deployment
2. It would enforce better testing practices

Docs: https://docs.travis-ci.com/user/deployment/google-app-engine/

**Comment by lukebjerring** [comment]
@rwaldron @boazsender - A decision for Bocoup.
My 5c: Requires _extreme_ scrutiny of PRs, and a very elaborate test suite (including webdriver test, perhaps?)

**Comment by lukebjerring** [comment]
This issue was moved to web-platform-tests/wpt.fyi#33
