### ISSUE TITLE
Identify and build a central server which identifies the correct SHA to be run and controls the other machines

### ISSUE THREAD

**Issue by mattl** [w3c/wptdashboard#395]
Subissue of https://github.com/w3c/wptdashboard/issues/394

**Comment by foolip** [comment]
@Hexcles FYI, I think there's some potential overlap here with how we measure import latency. For that we look at all wpt PRs and when they were merged, and thus get a more reliable latest bound on when all commits appeared. A service to pick a commit would also, at least as a side effect, learn something about when commits appeared.

@mattl, I'd be interested to hear a rough sketch of how this should work. If it's a "pick a commit, run everything, maybe timeout" cycle then actually the overlap wouldn't come naturally, and we should just share the same data for metrics calculation.

**Comment by mattl** [comment]
I was thinking pretty much exactly "pick a commit, run everything, maybe timeout"

**Comment by foolip** [comment]
Sounds good! That leaves measuring the latency entirely a separate problem, which is probably for the best.

**Comment by mattl** [comment]
Okay, so I have my code running and publishing the SHA at https://sha.wpt.fyi/ -- this is a cronjob running on a VM.

**Comment by mattl** [comment]
As this machine will also control the other machines, so I'm marking this as complete.
