### ISSUE TITLE
Generate a copy of the repo at specified SHA and loop through directories therein

### ISSUE THREAD

**Issue by mattl** [w3c/wptdashboard#396]
Subissue of https://github.com/w3c/wptdashboard/issues/394

**Comment by foolip** [comment]
https://github.com/foolip/ecosystem-infra-stats/blob/1c7791b779e5d7bd9acd327fd870da6b3bb10994/chromium-wpt-owners.sh has my notion of what an interesting directory in wpt is: all top-level directories except css/, and css/*.

**Comment by jugglinmike** [comment]
We've decided to run the tests in smaller subsets by using the "chunking" feature of the WPT CLI tool. This obviates the need for a "test discovery" shell script, so I am closing this issue.
