### ISSUE TITLE
When the machine receives a payload, it is verified (n% of tasks passed) and saved locally. Another payload is sent to machines in the pool.

### ISSUE THREAD

**Issue by mattl** [w3c/wptdashboard#399]
Subissue of https://github.com/w3c/wptdashboard/issues/394

**Comment by foolip** [comment]
I guess this would also resolve https://github.com/w3c/wptdashboard/issues/234?

**Comment by mattl** [comment]
Yep. That's the plan.

**Comment by mattl** [comment]
Rick suggests using the manifest tool to work out the number of test files as part of this.
