### ISSUE TITLE
Chrome runs are outdated

### ISSUE THREAD

**Issue by mattl** [w3c/wptdashboard#401]
This was my fault, I had a bad version of run.py on the machine, and have fixed it. Hoping to see a new run today/tomorrow but will keep this open to track things.

cc @foolip

**Comment by mattl** [comment]
Currently, they seem to be failing on webdriver tests.

https://gist.github.com/mattl/c40200311698ac622ae83be84c95e14f

@kereliuk @foolip

**Comment by foolip** [comment]
@kereliuk is OOO until Feb 3. @mattl, any way of just skipping the webdriver/ directory? Just deleting it in the checkout might do the trick.

**Comment by mattl** [comment]
Deleting it brought it back, so I have temporarily added `['rm','-rf','webdriver'],` to the script after the git checkout, before the manifest is run.

**Comment by gsnedders** [comment]
You're still running against Chrome 63, right? If it's against a more recent Chrome, it could just be ChromeDriver not working against unstable Chrome releases.

**Comment by mattl** [comment]
Yeah, Chrome 63.

**Comment by mattl** [comment]
We had two successful runs over the weekend, manually uploaded today.

**Comment by foolip** [comment]
Fine with me to close this now since there has been a new run.

**Comment by jugglinmike** [comment]
Closing as requested!
