### ISSUE TITLE
Future work to add a new field called committed_at which contains the commit time for the SHA 

### ISSUE THREAD

**Issue by mariestaver** [w3c/wptdashboard#402]
ref #154   
(Be aware, this may be a hassle at all three levels of the app)

Tasks:
- [ ] Update shared model to include commit_date
- [ ] Update GCP entity
- [ ] Backfill commit dates

**Comment by rwaldron** [comment]
run/run.py is updated here: https://github.com/w3c/wptdashboard/pull/383

**Comment by lukebjerring** [comment]
This issue was moved to web-platform-tests/wpt.fyi#11
