### ISSUE TITLE
Preserve all build records from ci.wpt.fyi so that it can be transitioned

### ISSUE THREAD

**Issue by mariestaver** [w3c/wptdashboard#411]
See email thread for an export dump from @jeffcarp and instructions for restoring the backup -- per @rwaldron, we'd like to preserve all build records for metrics purposes.  Please update this issue when this restore/transfer is complete, so that @foolip and team can transition this URL to another instance.

**Comment by mattl** [comment]
Can confirm this worked, I've shut the machine down but we have the data.
