### ISSUE TITLE
Discuss where tests will be run

### ISSUE THREAD

**Issue by jeffcarp** [w3c/wptdashboard#42]
The [design doc](https://bit.ly/wptdashboard-design-doc) describes running tests on [LUCI](https://github.com/luci), however this involves a few bits of custom work that aren't applicable to running the tests elsewhere, including using CIPD for distributing browsers and webdrivers, and setting up recipes. If forkability is a key focus, we may want to re-evaluate where tests will be run.

Right now all tests are being run on VMs @jeffcarp set up as a stepping stone.

cc @bobholt @foolip

**Comment by foolip** [comment]
Quoting myself from an old email:
- Technology choices are not something I feel strongly about, as long as the end result is reliable.
- However, it should be fairly easy to set up a new instance of the running infrastructure and dashboard including historical data. This adds credibility to the project, as neither Google nor Bocoup will be a gatekeeper.

In other words, we'd like forkability, and I think this implies that even if it's possible to run tests on LUCI, it should at the very least be possible to do the same on public infrastructure, in the simplest case physical, dedicates machines running the requisite OSes.
