### ISSUE TITLE
`run.py`: Implement tests

### ISSUE THREAD

**Issue by jugglinmike** [w3c/wptdashboard#428]
The `run.py` currently has minimal testing coverage. To promote safety during
feature addition and refactoring (e.g. gh-426), test coverage should be
improved.

(Because we are not yet sure of the way we will distribute concurrent test
execution, I will be writing these tests in a high-level integration style,
which stub out the `wpt` binary provided by the Web Platform Tests project.
This should help ensure the tests stay relevant across future refactorings.)

**Comment by mariestaver** [comment]
Functional tests are added -- more will be added as needed -- closing issue
