### ISSUE TITLE
Profile the number and frequency of intermittent test errors

### ISSUE THREAD

**Issue by jugglinmike** [w3c/wptdashboard#431]
Investigate which test files intermittently cause errors in the testing infrastructure and estimate the frequency of these errors. (This information will help us prioritize subsequent troubleshooting efforts.)

This depends on the improved logging functionality described in gh-430.

**Comment by jugglinmike** [comment]
Some notes:

- https://github.com/w3c/wptdashboard/issues/234#issuecomment-365358893
- [wpt.fyi: An observation on holes in the UI](https://groups.google.com/a/chromium.org/forum/#!topic/ecosystem-infra/j867Lg7Q7zA) (mailing list posting)

**Comment by jugglinmike** [comment]
As a result of the above, we're splitting this investigation into three more direct questions:

- [gh-441 - Safari and Edge time out when run from Amazon EC2 instances](https://github.com/w3c/wptdashboard/issues/441)
- [gh-478 - Research: Why do non-Sauce Labs browsers report fewer than 100% of results?](https://github.com/w3c/wptdashboard/issues/478)
- [gh-479 - Research: Why do Sauce Labs browsers time out when managed from ByteMark?](https://github.com/w3c/wptdashboard/issues/479)

**Comment by mariestaver** [comment]
Closing as this work is covered by the above issues.
