### ISSUE TITLE
Documentation for metrics/run/collect_metrics.go

### ISSUE THREAD

**Issue by rwaldron** [w3c/wptdashboard#433]
We need to have documentation of the following: 

- Environmental dependencies
- How does this run?
- When does this run?
- What does successful output (presently) look like?

**Comment by foolip** [comment]
Ping @mdittmer

**Comment by rwaldron** [comment]
@mdittmer in the future, if you add "Fixes gh-XYZ" to the commit message, where "XYZ" is the issue number, the issue will auto close when the commit lands.
