### ISSUE TITLE
Cron's `@reboot` feature is flaky on Ubuntu

### ISSUE THREAD

**Issue by jugglinmike** [w3c/wptdashboard#437]
This is a known issue with the Ubuntu distribution of GNU/Linux. @mattl: would you mind adding a reference to the bug reports you found on the topic?

We may be able to side-step this by switching to Debian.

**Comment by mattl** [comment]
I need to add details here.

**Comment by jugglinmike** [comment]
We haven't experienced this problem in the two months since it was reported, making it difficult to diagnose further. I'm going to close this issue for now; if this becomes a problem again, we can re-open and continue investigation.
