### ISSUE TITLE
Chrome sometimes fills the disk with temporary profile directories

### ISSUE THREAD

**Issue by jugglinmike** [w3c/wptdashboard#440]
This problem occurs very infrequently, so we don't know the cause of this yet. It has been confirmed by the Chrome team and potentially resolved. (@mattl: could you add a reference to the bug report you found?)

Workaround: Reboot the machine

**Comment by mattl** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=265642 (closed and verified in 2013)

**Comment by jugglinmike** [comment]
Experiencing this again today.

https://bugs.chromium.org/p/chromium/issues/detail?id=765398 is a more relevant bug report (and still open)

**Comment by mattl** [comment]
I'm going to add https://serverfault.com/questions/183821/rm-on-a-directory-with-millions-of-files/328305#328305 to browser-runner.sh

**Comment by mattl** [comment]
https://github.com/bocoup/wptd-ansible/blob/master/files/root/browser-runner.sh#L13-L14

**Comment by mattl** [comment]
Deleting these files in the browser-runner.sh script before a run doesn't seem to work. Not sure if deleting them after a run would work either. Rebooting the machine after each run may be the solution.

**Comment by mattl** [comment]
For now, rebooting this machine after the run as part of browser-runner.sh.

Make a patch to include this into the version of browser-runner.sh in master (and deploy it, via Ansible to current 4 machines)

**Comment by jugglinmike** [comment]
We currently handle this case with a dedicated build step which follows every "chunk" execution. These segments of the full WPT suite are small enough (and the workers' disks are spacious enough) to accommodate any "leaked" temporary files. In the future, I would be interested in more generic solutions (e.g.  via full system restart or via usage of disposable LXC containers), but the current solution appears to be sufficient for our immediate needs.
