### ISSUE TITLE
Write ansible playbooks to make test running machines reproducible 

### ISSUE THREAD

**Issue by mattl** [w3c/wptdashboard#449]

**Comment by mattl** [comment]
This is looking very good.

**Comment by mattl** [comment]
Added a few more pieces today, and we agreed to put it in the wptdashboard repo.

**Comment by mariestaver** [comment]
- [ ] Test 
- [ ] Implement log rotation
- [ ] Implement secrets management
- [ ] Implement reboot scheduling
- [ ] Deploy to production
