### ISSUE TITLE
Chunking run.py seems to repeatedly download browser and geckodriver

### ISSUE THREAD

**Issue by mattl** [w3c/wptdashboard#455]
Running chunk 62 of 100 (attempt 1 of 3)
 0:00.00 INFO Installing browser
Using webdriver binary /home/ubuntu/web-platform-tests/_venv/bin/geckodriver
Downloading gecko prefs
 0:10.82 INFO Updating test manifest /home/ubuntu/web-platform-tests/MANIFEST.json

**Comment by jugglinmike** [comment]
We addressed this issue via the introduction of a Buildbot-driven infrastructure (see gh-522).
