### ISSUE TITLE
wpt.fyi site deployment is broken

### ISSUE THREAD

**Issue by rwaldron** [w3c/wptdashboard#456]
@lukebjerring @mdittmer 

```
Updating service [default]...failed.
ERROR: (gcloud.app.deploy) Error Response: [9] Deployment contains files that cannot be compiled: Compile failed:
/work_dir/anomaly_handler.go:34: undefined: metrics.GetDatastoreKindName
/work_dir/anomaly_handler.go:35: undefined: metrics.PassRateMetadata
/work_dir/anomaly_handler.go:37: undefined: metrics.PassRateMetadata
/work_dir/anomaly_handler.go:69: undefined: metrics.GetDatastoreKindName
/work_dir/anomaly_handler.go:70: undefined: metrics.FailuresMetadata
/work_dir/anomaly_handler.go:74: undefined: metrics.FailuresMetadata
/work_dir/interop_handler.go:20: undefined: metrics.GetDatastoreKindName
/work_dir/interop_handler.go:20: undefined: metrics.PassRateMetadata
/work_dir/interop_handler.go:23: undefined: metrics.PassRateMetadata
2018/02/12 16:50:28 go-app-builder: build timing: 16×compile (4.175s total), 0×link (0s total)
2018/02/12 16:50:28 go-app-builder: failed running compile: exit status 2
```

**Comment by foolip** [comment]
@lukebjerring was telling me yesterday that something odd had happened to metrics data in prod, so this might be a consequence of that?

**Comment by lukebjerring** [comment]
No; that was with the metrics computation code. This looks like an import name mismatch.

**Comment by lukebjerring** [comment]
I just sync'd to head, and ran `./git/git-deploy` and it succeeded:
https://lukebjerring-upstream-master-dot-here-lift-this.appspot.com

It's likely that your local $GOPATH/src/github.com/w3c/wptdashboard folder is a symlink and there's something wrong with your imports. Have you tried deploying from the cloud console?

**Comment by mariestaver** [comment]
@lukebjerring @rwaldron is deployment for wptdashboard fixed?

**Comment by rwaldron** [comment]
@mariestaver I have an open PR to add installing the dependencies to the deployment process. @jugglinmike is reviewing.

**Comment by rwaldron** [comment]
Issue run down: 

1. For local development, the go deps are fetched and installed within the docker instance
2. The meager tests written for anomaly and interop (in main_test.go) are run in the docker instance
3. The site is run from the docker instance for development. 
4. git/git-deploy does not get executed from the docker instance, so unless the developer has explicitly run `go get github.com/w3c/wptdashboard/metrics` from their local (not in docker) environment, any deps that were installed in the docker instance will be missing from the deployment (which leads to the error I've encountered).
