### ISSUE TITLE
Troubleshooting:  Edge run has been stalled for ~24h

### ISSUE THREAD

**Issue by mariestaver** [w3c/wptdashboard#501]
We're pausing our ongoing work to stabilize and improve the system to address three runs that are not completing today.  Please use this issue to track the details of what we're trying and what works/doesn't.  Thanks!

**Comment by mattl** [comment]
Changed the Tunnel, but Sauce Labs is having some issues which have just been resolved. I'll keep looking on this, but it seems to be running along.

**Comment by mattl** [comment]
Double checked and Edge is running the latest code, so no #491 should happen here.

**Comment by mattl** [comment]
It's about 51% complete right now.

**Comment by mattl** [comment]
98% complete, we're almost there.

**Comment by mattl** [comment]
This has run a couple times now.
