### ISSUE TITLE
Troubleshooting:  Safari run has been stalled for ~24h

### ISSUE THREAD

**Issue by mariestaver** [w3c/wptdashboard#502]
We're pausing our ongoing work to stabilize and improve the system to address three runs that are not completing today.  Please use this issue to track the details of what we're trying and what works/doesn't.  Thanks!

**Comment by mattl** [comment]
Changed the Tunnel, but Sauce Labs is having some issues which have just been resolved. I'll keep looking on this, but it seems to be running along.

**Comment by mattl** [comment]
Restarted Safari after #491 happened due to the latest run.py not being on the machine.

**Comment by mattl** [comment]
Restarting a stalled Safari.

**Comment by mattl** [comment]
Safari ran to completion.
