### ISSUE TITLE
Deletion of temporary folder before its read

### ISSUE THREAD

**Issue by kereliuk** [w3c/wptdashboard#503]
When I try to do a run with run/run.py I get an error trying to open a file that doesn't exist.

`Traceback (most recent call last):
  File "run/run.py", line 596, in <module>
    main(args.platform_id, platform, args, config)
  File "run/run.py", line 226, in main
    expected_tests = get_expected_tests(raw_log_filename)
  File "run/run.py", line 382, in get_expected_tests
    with open(filename) as handle:
IOError: [Errno 2] No such file or directory: '/tmp/tmpSTEr8j-wptdashboard'
`

I believe we delete this folder with os.remove here https://github.com/w3c/wptdashboard/blob/master/run/run.py#L209
And then try to access it after.

**Comment by jugglinmike** [comment]
`run.py` does delete that file, but it is expected to be created by the subsequent invocation of the WPT CLI ([via the WPT CLI's `--log-raw` option](https://github.com/w3c/wptdashboard/blob/6a0f50d175d341a69939a15b7f65dae08b43ea2b/run/run.py#L189)).  The fact that it is not present is an indication that the WPT CLI has not run as expected.

This situation shouldn't crash `run.py`, but it also indicates a problem with the test invocation. You can view the output of that process by specifying `--log DEBUG` when invoking `run.py`.

**Comment by kereliuk** [comment]
You are right, there was another error (that made more sense) that I caught with adding log level. Works now. Thanks!
