### ISSUE TITLE
Process of adding a new browser

### ISSUE THREAD

**Issue by xfq** [w3c/wptdashboard#509]
I didn't find the process of adding a new browser to run web-platform-tests, uploading the results to Google Cloud Storage, and displaying the results in https://wpt.fyi/. It would be good to have such process documented.

For example, the process might include:

* Make sure `run/run.py` and the underlying wpt-tools support the new browser
* Add new key(s) in `webapp/browsers.json`
* Make sure the new browser vendor can run the tests and `gsutil rsync` to the wptd bucket
* etc.

The test results of the new browser need to be up-to-date and reliable too. An automatic filter can be added, for example, if the test results of a browser has not been updated for a long time, the test results of this browser won't be displayed on the home page of wpt.fyi since there is no point to see stale test results (the old test results may still be stored/archived in Google Cloud Storage, if it's useful).

**Comment by mariestaver** [comment]
Thank you, @xfq !  That's helpful information.  @isaacdurazo, can you add this to our roadmap for updating the wptdashboard documentation?

**Comment by isaacdurazo** [comment]
Sure thing, @mariestaver! and thanks @xfq

**Comment by foolip** [comment]
@xfq, this is very much related to https://github.com/w3c/wptdashboard/issues/290. Can you check if that captures the outcome that you're looking for? If so I'd like to close this issue, since I've pointed to https://github.com/w3c/wptdashboard/issues/290 from other places.

**Comment by xfq** [comment]
@foolip Yes, you're right. I'm not aware of that issue, sorry.

Closing.
