### ISSUE TITLE
Display open PRs touching the current directory

### ISSUE THREAD

**Issue by jgraham** [w3c/wptdashboard#523]
For some specs we have a large number of open PRs. One problem is getting the people who would benefit from the tests landing to be aware of the fact that there are a bunch of outstanding PRs for that spec. If they know this it seems plausible that they will go in and review those tests, at least in some cases. Displaying the existence of unlanded PRs on wpt.fyi could help draw attention to this.

**Comment by lukebjerring** [comment]
This issue was moved to web-platform-tests/wpt.fyi#4
