### ISSUE TITLE
https://wpt.fyi/test-runs has holes that are not "real" missing runs

### ISSUE THREAD

**Issue by foolip** [w3c/wptdashboard#524]
https://wpt.fyi/test-runs internally uses https://wpt.fyi/api/runs?max-count=100 and fills in the rows using that data.

It seems like the 100 limit is per browser (or something) which leads to funny results in the older part of the data. Right now, it looks like b0c75cd885 has only Edge and Safari runs, but in https://wpt.fyi/?sha=b0c75cd885 one can see Chrome and Firefox as well. They also show up in https://wpt.fyi/api/runs?max-count=1000.

I noticed this when working on https://github.com/foolip/ecosystem-infra-stats/issues/6, because when I calculated which runs were "complete", the last few ones didn't look complete on https://wpt.fyi/test-runs.

Fix? Perhaps to not use any runs older than the oldest available run for any individual browser when presenting the data, or do change the API to avoid the problem.

**Comment by lukebjerring** [comment]
This issue was moved to web-platform-tests/wpt.fyi#3
