### ISSUE TITLE
Give people a way to fetch an index of all TestRuns

### ISSUE THREAD

**Issue by jeffcarp** [w3c/wptdashboard#73]
I'm about to land #70 describing how to access public data if you know the parameters beforehand, but there's no way to retrieve historical data without doing an exhaustive search of all possible SHAs and platform IDs.

This could take the form of a scheduled job that enumerates all uploaded data and uploads a file `testruns.json` to the root of the bucket.

**Comment by jeffcarp** [comment]
An index is now available at https://storage.googleapis.com/wptd/testruns-index.json but that file is not regularly updated.

**Comment by JKereliuk** [comment]
How often are the tests run? Is there any way to currently access what SHA/platforms are available with date information (other than looking up the date from the first 10 characters of the SHA).

**Comment by lukebjerring** [comment]
This issue was moved to web-platform-tests/wpt.fyi#30
