### ISSUE TITLE
Ahem not installed

### ISSUE THREAD

**Issue by gsnedders** [w3c/wptdashboard#87]
Plenty of reftests (and some testharness.js tests) rely on Ahem being installed; we appear not to have it installed.

**Comment by bobholt** [comment]
@jgraham How do we handle this in the CI jobs? I don't see anything installing Ahem.ttf on Travis. Some CSS tests (mostly /css/vendor-imports/mozilla/mozilla-central-reftests/) carry their own local Ahem.ttf in the `support` directory [in other news, there are many copies of Ahem.ttf in web-platform-tests], but I don't see anything in our CI scripts or Travis config installing that font on the machine for the tests that expect it to be installed.

**Comment by jgraham** [comment]
It's probably broken there as well.

**Comment by gsnedders** [comment]
Most of the groundwork for this is done by https://github.com/w3c/web-platform-tests/pull/7322, just need to change the runner here to pass the right option.

**Comment by bobholt** [comment]
@gsnedders Correct. I wanted to give https://github.com/w3c/web-platform-tests/pull/7322 a day to sit before we rely on it here.
