### ISSUE TITLE
"Test file" results?

### ISSUE THREAD

**Issue by mikewest** [w3c/wptdashboard#92]
https://w3c-test.org/cookies/secure/set-from-ws.https.sub.html contains a single test, but http://wpt.fyi/cookies/secure/set-from-ws.https.sub.html  (and the table at http://wpt.fyi/cookies/secure) counts two.

**Comment by jgraham** [comment]
This is expected. One result is the overall file result, which is typically `OK` but can be `ERROR`, `TIMEOUT`, `CRASH`, etc. The other is the result of the single subtest.

**Comment by mikewest** [comment]
Ok. I guess it seems strange to count that as a test in the list of results (and especially on the wrap-up tables). It surprised me, at least. :)

**Comment by bobholt** [comment]
While expected, I agree it's odd. Leaving this open to consider how to more clearly distinguish overall file results from subtest results.

**Comment by gsnedders** [comment]
The fact it's under the table as a subtest is confusing IMO. I also think the colouring isn't that useful: "OK" isn't actually that interesting; what we want is "ERROR"/"TIMEOUT"/etc. when the parent fails and make it clear the actual subtest results below are basically irrelevant.

**Comment by lukebjerring** [comment]
This issue was moved to web-platform-tests/wpt.fyi#38
