### ISSUE TITLE
Reftests fail with ERROR on Chrome

### ISSUE THREAD

**Issue by foolip** [w3c/wptdashboard#97]
http://wpt.fyi/css/css-fonts-3

@kojiishi pointed out [on blink-dev](https://groups.google.com/a/chromium.org/d/msg/blink-dev/zNaJRd3tjw4/H4MOpm4ECwAJ) that many of these tests are imported in Chromium and pass there, so why are they failing in the wpt.fyi running infrastructure?

@kojiishi, do you have a specific test that you know if passing in content_shell but not on wpt.fyi?

**Comment by kojiishi** [comment]
As in the intent on blink-dev, we have shipped font-variant-caps, font-variant-ligatures, and font-variant-numeric. Picked `font-variant-caps-01.html` and it passes.

Tests we know Chrome fails are searchable in [TestExpectations](https://cs.chromium.org/chromium/src/third_party/WebKit/LayoutTests/TestExpectations?q=TestExpectations&dr), please search for "css-fonts-3".

**Comment by gsnedders** [comment]
Note they're ERROR and not FAIL which implies something is way more wrong than just the behaviour of the test. @jgraham was saying on IRC that reftests seem to be broken in Chrome now, and it indeed appears like *all* reftests ERROR in Chrome now.

**Comment by svgeesus** [comment]
They also pass when run manually. See for example
https://test.csswg.org/harness/results/css-fonts-3_dev/grouped/section/6.4/
https://test.csswg.org/harness/results/css-fonts-3_dev/grouped/section/6.6/
https://test.csswg.org/harness/results/css-fonts-3_dev/grouped/section/6.7/

**Comment by gsnedders** [comment]
(Fixed by the new ChromeDriver release)
